export const SEARCH_MOVIE_START = "SEARCH_MOVIE_START";
export const SEARCH_MOVIE_COMPLETE = "SEARCH_MOVIE_COMPLETE";
export const SEARCH_MOVIE_ERROR = "SEARCH_MOVIE_ERROR";

export const SEARCH_MOVIE_BY_ID_START = "SEARCH_MOVIE_BY_ID_START";
export const SEARCH_MOVIE_BY_ID_COMPLETE = "SEARCH_MOVIDE_BY_ID_COMPLETE";
export const SEARCH_MOVIE_BY_ID_ERROR = "SEARCH_MOVIE_BY_ID_ERROR";

export const MOST_POPULAR_MOVIE_START = "MOST_POPULAR_MOVIE_START";
export const MOST_POPULAR_MOVIE_COMPLETE = "MOST_POPULAR_MOVIE_COMPLETE";
export const MOST_POPULAR_MOVIE_ERROR = "MOST_POPULAR_MOVIE_ERROR";
